AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Generate AWS VPC and subnet

Parameters:
  EnviromentName:
    Description: The name of enviroment such as dev, staging and prod
    Type: String
    Default: dev
  VpcCidr:
    Description: the range of ip for VPC
    Type: String
    Default: dev

Resource:
    # 1. Tạo VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-vpc'
  
  